spring:
  application:
    name: expense-tracker
  datasource:
    url: jdbc:postgresql://localhost:5432/controledespesas?autoReconnect=true&useSSL=false
    username: postgres
    password: marisfelipe1805
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

logging:
  level:
    org:
      hibernate:
        type: trace


server:
  port: 8081